name: release

on:
  push:
    tags: 
      - v[0-9].[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Compile
      run: make compile

    - name: Upload s3analytics-darwin-amd64
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/s3analytics-darwin-amd64
        asset_name: s3analytics-darwin-amd64
        tag: ${{ github.ref }}

    - name: Upload s3analytics-windows-amd64.exe
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/s3analytics-windows-amd64.exe
        asset_name: s3analytics-windows-amd64.exe
        tag: ${{ github.ref }}

    - name: Upload s3analytics-linux-amd64
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/s3analytics-linux-amd64
        asset_name: s3analytics-linux-amd64
        tag: ${{ github.ref }}